logoText = "Î©"
logoType = "short" # long, short
description = "Notebook for long readings and nested content"



enableLandingBackground = true
enableLangChange = true
enableDarkMode = true
enableBlogBreadcrumb = true
enableEditBtn = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true


tocFolding = true
tocPosition = "outer" # inner, outer
itemsPerCategory = 5
sidebarPosition = "left"
enableSidebarPostsByOrder = true